{"name": "test_login_with_wrong_password", "status": "passed", "description": "Проверка входа с неверным паролем", "attachments": [{"name": "log", "source": "c5ef0b1c-8080-4bc3-a150-cd01703db63a-attachment.txt", "type": "text/plain"}], "start": 1758714052506, "stop": 1758714052656, "uuid": "63159bd1-a84d-4ec4-8d47-76efdcf55845", "historyId": "e766f7c22dd9011f4fc0a5b0dd47ef53", "testCaseId": "e766f7c22dd9011f4fc0a5b0dd47ef53", "fullName": "tests.api.test_auth_api#test_login_with_wrong_password", "labels": [{"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_auth_api"}, {"name": "host", "value": "DESKTOP-JVPC402"}, {"name": "thread", "value": "18196-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_auth_api"}], "titlePath": ["tests", "api", "test_auth_api.py"]}