{"name": "test_login_with_wrong_password", "status": "passed", "description": "Проверка входа с неверным паролем", "attachments": [{"name": "log", "source": "4ec7aadb-78dd-4a19-9ced-88883aadc486-attachment.txt", "type": "text/plain"}], "start": 1758713969872, "stop": 1758713970016, "uuid": "7285e593-c734-44b3-bb11-3a0d7f947e54", "historyId": "e766f7c22dd9011f4fc0a5b0dd47ef53", "testCaseId": "e766f7c22dd9011f4fc0a5b0dd47ef53", "fullName": "tests.api.test_auth_api#test_login_with_wrong_password", "labels": [{"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_auth_api"}, {"name": "host", "value": "DESKTOP-JVPC402"}, {"name": "thread", "value": "17916-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_auth_api"}], "titlePath": ["tests", "api", "test_auth_api.py"]}