{"name": "test_login_with_wrong_password", "status": "passed", "description": "Проверка входа с неверным паролем", "attachments": [{"name": "log", "source": "411eb029-8c68-4e62-832f-1e3cd8830f7b-attachment.txt", "type": "text/plain"}], "start": 1758713472782, "stop": 1758713472930, "uuid": "4b606ecb-06c0-4c9c-a090-2ec5286399e0", "historyId": "e766f7c22dd9011f4fc0a5b0dd47ef53", "testCaseId": "e766f7c22dd9011f4fc0a5b0dd47ef53", "fullName": "tests.api.test_auth_api#test_login_with_wrong_password", "labels": [{"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_auth_api"}, {"name": "host", "value": "DESKTOP-JVPC402"}, {"name": "thread", "value": "12016-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_auth_api"}], "titlePath": ["tests", "api", "test_auth_api.py"]}